services:
  front:
    build: ./cocowattreact
    environment:
      - http://localhost:8081/api
    ports:
      - 80:81
    networks:
      todo_network:
        ipv4_address: 10.5.0.4
    links:
      - api
    depends_on:
      - api
  api:
    build: ./cocowattreactApi
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/cocowatt
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=test
    networks:
      todo_network:
        ipv4_address: 10.5.0.2
    links:
      - db
    depends_on:
      - db
    restart: always


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: test
      #MYSQL_DATABASE: spring_blog_dto
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      todo_network:
        ipv4_address: 10.5.0.3
volumes:
  data:

networks:
  todo_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16